version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: myapp

  echo-test:
    image: alpine:latest
    command: echo "Docker Compose is up and running!"

  database:
    image: postgres:15
    container_name: postgres_database
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5