version: 2.1
orbs:
  conjur-circleci: cyberark/conjur-circleci-orb@0.0.1
jobs:
  run-job:
    docker:
      - image: cimg/base:current
    steps:
      - run: "echo Hello"
      - run: "echo Goodbye Earth"
      - conjur-circleci/retrieve_secret:
          url: "https://conjur_appliance_url"
          secrets: "data/circleci/apps/safe/secret2|sql_username;data/circleci/apps/safe/secret1;"

workflows:
  use-my-orb:
    jobs:
      - run-job